### ISSUE TITLE
Subscribe & Unsubscribe won't accept list

### ISSUE THREAD

**Issue by DJDevon3** [adafruit/Adafruit_CircuitPython_AdafruitIO#102]
This works
```py
io.subscribe("BME280-Unbiased")
io.subscribe("BME280-RealTemp")
```
attempting to subscribe to 2 feeds simultaneously doesn't work. here are a few of the iterations I tried.
```py
io.subscribe("BME280-Unbiased", "BME280-RealTemp")
io.subscribe([("BME280-Unbiased", "BME280-RealTemp")])
io.subscribe([('BME280-Unbiased'), ('BME280-RealTemp')])
```
[According to the docs](https://docs.circuitpython.org/projects/adafruitio/en/latest/api.html#adafruit_io.adafruit_io.IO_MQTT.subscribe)
```py
client.subscribe([('temperature'), ('humidity')])
```
should work but does not, returns 
`TypeError: can't convert 'list' object to str implicitly`

**Comment by tyeth** [comment]
Appears that the docs have been updated to not accept a list (except for `publish_multiple`. Closing this for now
