### ISSUE TITLE
Publish_Multiple default 3 second timeout

### ISSUE THREAD

**Issue by DJDevon3** [adafruit/Adafruit_CircuitPython_AdafruitIO#103]
This is a documentation clarification request.

I ran into an issue where I thought using publish_multiple was for publishing multiple feeds at the same time.  There is a 3 second delay between publishing each item (in a list you specify) by default which [isn't explicitly documented](https://docs.circuitpython.org/projects/adafruitio/en/latest/api.html#adafruit_io.adafruit_io.IO_MQTT.publish_multiple).  I thought if no timeout was specified it would be 0. This is an assumption issue on my part yes but something worth making more clear in documentation.

this will publish both feeds simultaneously with the same timestamp
```py
io.publish("temperature", temperature_value)
io.publish("humidity", humidity_value)
```

this will publish both feeds 3 seconds apart
```py
io.publish_multiple([("temperature", temperature_value), ("humidity", humidity_value)])
```

my expectation was publish_multiple would publish both simultaneously and individual publishes would be buffered. It works completely the opposite of how I expected.  Again this is an assumption issue on my part but something worth putting down on paper.

**Comment by tyeth** [comment]
Appears to now be documented, closing this issue
