### ISSUE TITLE
io.get_feed wrong number of arguments

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/Adafruit_CircuitPython_AdafruitIO#115]
A [forum user](https://forums.adafruit.com/viewtopic.php?t=207443) reported that a [simple Pico W AIO example](https://learn.adafruit.com/pico-w-wifi-with-circuitpython/pico-w-with-adafruit-io) script was failing. 

I was able to reproduce the same error using a Pico W loaded with CP 8.2.6 and the current adafruit_io / adafruit_requests library releases. 

```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
connected to io
Traceback (most recent call last):
  File "code.py", line 33, in <module>
  File "adafruit_io/adafruit_io.py", line 748, in get_feed
  File "adafruit_io/adafruit_io.py", line 578, in _get
  File "adafruit_requests.py", line 732, in get
  File "adafruit_requests.py", line 674, in request
  File "adafruit_requests.py", line 615, in _send_request
  File "adafruit_requests.py", line 560, in _send_header
  File "adafruit_requests.py", line 555, in _send_as_bytes
TypeError: wrong number of arguments

Code done running.
```

I tried going to CP9.x and rolling back to earlier releases of CP8.x as well as the libraries, but the error persists. 

This is the relevant section of the [code.py](https://learn.adafruit.com/pico-w-wifi-with-circuitpython/pico-w-with-adafruit-io) that triggers the problem.

```
try:
# get feed
    picowTemp_feed = io.get_feed("pitemp")
    picowHumid_feed = io.get_feed("pihumid")
except AdafruitIO_RequestError:
# if no feed exists, create one
    picowTemp_feed = io.create_new_feed("pitemp")
    picowHumid_feed = io.create_new_feed("pihumid")
```

**Comment by brentru** [comment]
Transferred this issue from Adafruit CircuitPython Requests to Adafruit IO CircuitPython

**Comment by User-764Q** [comment]
Thanks, the merged file fixed my issue :-{)

**Comment by FoamyGuy** [comment]
resolved by: https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/152
