### ISSUE TITLE
add_feed_to_group() is not working - used adafruit_io_groups.py example as a test case.

### ISSUE THREAD

**Issue by thejunglejim** [adafruit/Adafruit_CircuitPython_AdafruitIO#119]
Running the `adafruit_io_groups.py` example causes the following error:

`Adafruit IO Error 404: not found - API documentation can be found at https://io.adafruit.com/api/docs`

The line causes that error:
https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/blob/c9ad360969a4c5f26aa172c2f945b7b389fa4a3c/examples/adafruit_io_http/adafruit_io_groups.py#L68

**Comment by thejunglejim** [comment]
Using the `add_feed_to_group()` call is still **NOT** working - It giver the error: `Adafruit IO Error 404: not found - API documentation can be found at https://io.adafruit.com/api/docs`

I looked at the code in the library `adafruit_io.py` and it seems fine but I'm no expert ;-)  The docs say it will add an **existing** feed to a group. https://docs.circuitpython.org/projects/adafruitio/en/latest/api.html#adafruit_io.adafruit_io.IO_HTTP.add_feed_to_group
 It seems to create the correct path/url 

When using Curl to call the API directly, it does do something a little strange. It creates a brand **new** feed under the specified group i.e. If I have a feed called `test` under my general feeds, it will create a **new** feed called test under the group I specify.  I will now have two `test` feeds.
`curl -F 'feed_key=test' -H "X-AIO-Key: XXX" https://io.adafruit.com/api/v2/XXX/groups/envsensors/add`

**Comment by thejunglejim** [comment]
I believe I found the bug - It is the API. 
It wants a feed that already exists ....  but then goes and creates a need feed in the group regardless.

Not sure how to re-open this issue

**Comment by tyeth** [comment]
Ignoring the Curl option for one moment...
I didn't get two feeds of the same name created when running the newer
group example, although it looks initially like that on the website, but
instead it gets associated to two groups.
Check the feed test, you should see it is one feed with two entries in the
groups collection.

If you alter the new group demo to re-fetch the humidity group where it
re-fetches the latest group data, and print it, you should see the feed has
two groups associated (the original - default in this case - and envvars or
whatever was passed to add_feed_to_group). You could add a pause, or
comment out the deletion code, then inspect the website and fetch the feed
data freshly again then print the objects/json.

**Comment by thejunglejim** [comment]
A feed can belong to more than one group but it is still the same feed - now it makes sense.

Thanks [@tyeth ](https://github.com/tyeth) for the help and explanation.
