### ISSUE TITLE
Invalid feedname results in no error client or server side

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/Adafruit_CircuitPython_AdafruitIO#67]
I was doing this... 

    _mqtt_key = f"{aio_username}/feeds/{feed_name}"
    aio.publish(_mqtt_key, value)

instead of 

    aio.publish(feed_name, value)

And I got no error client side or in the io.adafruit.com monitoring page.
Took me forever to figure out why it wasn't working... :-)

**Comment by brentru** [comment]
https://forums.adafruit.com/viewtopic.php?f=56&t=175681&p=862814#p862814

**Comment by brentru** [comment]
@askpatrickw  I can confirm this occurs when attempting to publish to `io.publish("brubell/feeds/temp", 1)` and also with subscribe `client.subscribe("brubell/feeds/temperature")`.

This library should perform validation across any method which access feed keys using the following rules via https://learn.adafruit.com/naming-things-in-adafruit-io/the-two-feed-identifiers:
1) The only characters we permit are lower case English letters ("a" to "z"), numbers, and dash ("-").
2) The name must be a maximum length of 128 characters.

**Comment by jposada202020** [comment]
@askpatrickw I thiink chnges related with this issue we introduced in https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/pull/68. Let me know if this is the case. Thanks :)

**Comment by brentru** [comment]
@jposada202020  Confirming that this issue was address in #68, closing.
