### ISSUE TITLE
Accessing grouped feeds

### ISSUE THREAD

**Issue by xadhoom** [adafruit/Adafruit_CircuitPython_AdafruitIO#71]
Hi!

I've recently updated the io_library and my code stopped working because of this https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/commit/817574c5b7552d877a2c6f189ce1c789a298deaf .

A sample code is (taken from adafruit website):
```
feed_aqi = io.get_feed("air-quality-sensor.aqi")
feed_aqi_category = io.get_feed("air-quality-sensor.category")
```

Now the key is invalid, because it contains a dot.

Is that a regression or maybe there's a better way to handle group feeds?

**Comment by flavio-fernandes** [comment]
Hello!
Yes, I this this is a regression introduced here:
https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/commit/1e3d458ccbe86dade80ce3005a41ffed5d50b864#diff-6c23e9d7816b23ad2608e33b531be2a30e68566e5885117f4c3e872e7d60b879R43

The validate should allow '.' for groups. Agree @brentru  ?

**Comment by brentru** [comment]
@flavio-fernandes  Yeah, it should allow periods for group names. @dherrada  brought this up to me a week ago as well.

**Comment by dherrada** [comment]
@flavio-fernandes Yeah. Thanks for doing that. I was planning on doing it but it completely slipped my mind.

**Comment by flavio-fernandes** [comment]
> @flavio-fernandes Yeah. Thanks for doing that. I was planning on doing it but it completely slipped my mind.

np. I hope the change is good now.
