### ISSUE TITLE
aio_password should be aio_key

### ISSUE THREAD

**Issue by scarolan** [adafruit/Adafruit_CircuitPython_AdafruitIO#92]
Small issue with the tutorial here:
https://learn.adafruit.com/quickstart-rp2040-pico-with-wifi-and-circuitpython/usage-with-adafruit-io

It asks you to configure secrets.py with `aio_password` but the code example wants `aio_key`.

**Comment by brentru** [comment]
@scarolan Thanks for reporting an issue. I've updated the tutorial page to reflect this.

**Comment by scarolan** [comment]
You guys are the best!  Thank you for CircuitPython 🐍
