### ISSUE TITLE
send_batch_data requires class instances when it should just require accept a list or dict

### ISSUE THREAD

**Issue by evaherrada** [adafruit/Adafruit_CircuitPython_AdafruitIO#94]
https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/blob/main/adafruit_io/adafruit_io.py#L607

The _asdict method needs to be run on an instance of a class to get the class attributes. It would be easier for most users to just send a list or dict.

**Comment by evaherrada** [comment]
cc @brentru

**Comment by brentru** [comment]
@evaherrada  Do you want to work on this issue next week? Tag me when there's a PR ready for review

**Comment by rbrian** [comment]
I’m available to help however I can, at the very least for testing.

**Comment by tyeth** [comment]
Closing this after merging #125 and releasing v5.9.0
